# Generated by Django 3.2.4 on 2021-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210806_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='возраст'),
        ),
    ]
